### ISSUE TITLE
Perform a build use

### ISSUE THREAD

**Issue by MicheleFoderaro** [uniquid/uidcore-java#6]
Hi,
When I try to perform a full build use using the command "MVN clean package", I get the following error:

"Could not resolve dependencies for project com.uniquid:node:jar:0.1-RC1-SNAPSHOT: The following artifacts could not be resolved: org.bitcoinj:bitcoinj-core-uniquid:jar:0.14.5, com.uniquid:utils:jar:1.0-SNAPSHOT: Failure to find org.bitcoinj:bitcoinj-core-uniquid:jar:0.14.5 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced"

I think problem is that on Maven Central this kind of artifact does not exist, or it is bad declared in pom.xml. Can you update o help me to resolve this error?

Thanks a lot.

**Comment by gmagnotta** [comment]
Hi,

probably you are missing some uniquid dependencies.

Please follow instructions at https://github.com/uniquid/developer-wiki/blob/master/java_requirements.md

Regards,
Giuseppe

**Comment by MicheleFoderaro** [comment]
Hi, 

I am following the guide, so I created a directory where I put into the content of bitcoinj "https://github.com/uniquid/bitcoinj". After, I do this command: "mvn release:branch -DbranchName=release-0.14-uniquid" and it asks me the new working copy version. What I should insert into? I try with the number of version and the name of the modules, but it doesn't work. 

Thanks a lot
![provamichele](https://user-images.githubusercontent.com/25589939/35627537-740a8cca-0699-11e8-9fab-f39bebd6a049.png)

**Comment by gmagnotta** [comment]
Hi Michele,

in the document there isn't any reference to "mvn release:branch" command.

You have to clone the repository. Then you have to checkout the branch 'release-0.14-uniquid' with "git checkout release-0.14-uniquid". Finally you have to issue the command "mvn clean package install".

Regards,
Giuseppe
